/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRoles } from "./IRoles";
export type { ITreasuryRouter } from "./ITreasuryRouter";
export type { IVotingPowerStrategy } from "./IVotingPowerStrategy";
