import './globals.css'
import '@rainbow-me/rainbowkit/styles.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { WagmiConfigProvider } from "@/components/providers/wagmi-provider"
import Navbar from "@/components/navbar"
import Footer from "@/components/footer"

if (typeof window !== "undefined") {
  localStorage.setItem("debug", "walletconnect:*");
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <WagmiConfigProvider>
          <Navbar />
          {children}
          <Footer />
        </WagmiConfigProvider>
      </body>
    </html>
  )
}
