/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITreasuryRouter,
  ITreasuryRouterInterface,
} from "../../../contracts/interfaces/ITreasuryRouter";

const _abi = [
  {
    inputs: [],
    name: "receiveFunds",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ITreasuryRouter__factory {
  static readonly abi = _abi;
  static createInterface(): ITreasuryRouterInterface {
    return new Interface(_abi) as ITreasuryRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITreasuryRouter {
    return new Contract(address, _abi, runner) as unknown as ITreasuryRouter;
  }
}
