/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVotingPowerStrategy,
  IVotingPowerStrategyInterface,
} from "../../../contracts/interfaces/IVotingPowerStrategy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getVotingPower",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IVotingPowerStrategy__factory {
  static readonly abi = _abi;
  static createInterface(): IVotingPowerStrategyInterface {
    return new Interface(_abi) as IVotingPowerStrategyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVotingPowerStrategy {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IVotingPowerStrategy;
  }
}
